[package]
name = "aoc_2015"
version = "0.1.0"
authors = ["trox667 <trox667@googlemail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "day01"
path = "src/day01.rs"

[dependencies]
