[package]
authors = ["trox667 <trox667@googlemail.com>"]
edition = "2018"
name = "rust-sln"
version = "0.1.0"

[dependencies]
combinations = "*"
regex = "*"

[[bin]]
name = "day01"
path = "src/day01.rs"

[[bin]]
name = "day02"
path = "src/day02.rs"

[[bin]]
name = "day03"
path = "src/day03.rs"
